targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            "^lib/entity/habit/model/{{}}.dart": "lib/entity/habit/model/isar/{{}}.g.dart"
