name: perpetuity
description: "A free, feature-rich habit tracker"
publish_to: 'none'
version: 0.4.0

environment:
  sdk: ^3.8.1

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: 3.1.0+1
  jiffy: ^6.4.3
  path: ^1.9.1
  path_provider: ^2.0.15
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  generate: true
